services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  # Указываем контекст сборки (текущая директория)
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env

volumes:
  postgres_data: